apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: w47wqxiu0-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/w47wqxiu0-dotnet-basic-gitops